blank_issues_enabled: true
contact_links:
  - name: Security Policy
    url: https://github.com/itzzjustmateo/hydro-install/security/policy
    about: Please report security vulnerabilities privately
  - name: Hydrodactyl Panel
    url: https://github.com/BlueprintFramework/hydrodactyl
    about: Issues related to the Hydrodactyl panel software itself
  - name: Wings Daemon (Go)
    url: https://github.com/pterodactyl/wings
    about: Issues related to the Wings daemon software itself
  - name: Wings-RS Daemon (Rust)
    url: https://github.com/calagopus/wings
    about: Issues related to the wings-rs daemon software itself
  - name: Elytra Daemon (legacy)
    url: https://github.com/pyrohost/elytra
    about: Issues related to the legacy Elytra daemon
